In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("position_salaries.csv",encoding="latin-1")
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [2]:
x=df.iloc[:,:2].values #independent variables
y=df.iloc[:,2].values  #dependent variables
print(x)
print(y)


[['Business Analyst' 1]
 ['Junior Consultant' 2]
 ['Senior Consultant' 3]
 ['Manager' 4]
 ['Country Manager' 5]
 ['Region Manager' 6]
 ['Partner' 7]
 ['Senior Partner' 8]
 ['C-level' 9]
 ['CEO' 10]]
[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [4]:
from sklearn.preprocessing import LabelEncoder
lb_enco=LabelEncoder()
x[:,0]=lb_enco.fit_transform(x[:,0])
y=lb_enco.fit_transform(y)
print(x)
print(y)

[[0 1]
 [4 2]
 [8 3]
 [5 4]
 [3 5]
 [7 6]
 [6 7]
 [9 8]
 [1 9]
 [2 10]]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .25)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[0 1]
 [6 7]
 [8 3]
 [9 8]
 [2 10]
 [3 5]
 [1 9]]
[0 6 2 7 9 4 8]
[[4 2]
 [7 6]
 [5 4]]
[1 5 3]


C:\Users\acer\Anaconda35\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [12]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

nb.fit(x_train, y_train)
nb.score(x_train, y_train)

predicted= nb.predict(x_test)    #Predict Output
print(predicted)


[4 6 4]


In [17]:
import numpy as np
from sklearn.metrics import mean_squared_error
print(np.sqrt(mean_squared_error(y_test,predicted)))

1.91485421551


In [18]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusionmetrics=confusion_matrix(y_test,predicted)
print( "confusion metrics :",confusionmetrics)
print("accuracy is",accuracy_score(y_test,predicted)*100)

confusion metrics : [[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
accuracy is 0.0
